### ISSUE TITLE
Hello, when can acpid be updated to support 7.1-42661?

### ISSUE THREAD

**Issue by Honanhui** [jimmyGALLAND/redpill-ext#7]
Hello, when can acpid be updated to support 7.1-42661? It seems that only your acpid can support power key shutdown at present

**Comment by Honanhui** [comment]
Hello, your latest acpid driver has been updated, but 3622-7.1-42661 can no longer support power key shutdown

**Comment by jimmyGALLAND** [comment]
Hi Honanhui, 
I think I have fixed the problem for broadwell architecture.
Could you confirm with your test config?
I tested with virtualbox

**Comment by jimmyGALLAND** [comment]
And test with broadwellnk  7.1 OK

**Comment by Honanhui** [comment]
OK, I'll test it later.

**Comment by Honanhui** [comment]
Thank you very much. 3622 has been successfully installed, and the power button can turn off normally.

发自我的iPhone
