### ISSUE TITLE
Why can't I shut down or restart in jun mode?

### ISSUE THREAD

**Issue by Honanhui** [jimmyGALLAND/redpill-ext#9]
Why can't I shut down or restart in jun mode?

Version is 3622 7.1-42661 up4

**Comment by jimmyGALLAND** [comment]
This github is no longer maintained, please choose the one corresponding to your situation
(now ACPI is included in loaders)

If you use Fabio's Arpl
 https://github.com/fbelavenuto/arpl

If you use pocopico'stinycore
https://github.com/pocopico/tinycore-redpill
